Repository Afterburner2024/Afterburner-Backend, pull requests merged in 2024-10, with the labels that each got.

#1 feat:community post
  build.gradle
  src/main/java/com/afterburner/community/controller/CommunityController.java
  src/main/java/com/afterburner/community/model/Community.java
  src/main/java/com/afterburner/community/model/CommunityDTO.java
  src/main/java/com/afterburner/community/model/CommunityStatus.java
  src/main/java/com/afterburner/community/repository/CommunityRepository.java
  src/main/java/com/afterburner/community/service/CommunityService.java
  src/main/java/com/afterburner/study/controller/StudytController.java
  src/main/java/com/afterburner/study/model/Study.java
  src/main/java/com/afterburner/study/model/StudyDTO.java
  src/main/java/com/afterburner/study/repository/StudyRepository.java
  src/main/java/com/afterburner/study/service/StudyService.java
Labels: 진행 중

#2 feat:시큐리티 컨피그, jwt필터
  src/main/java/com/afterburner/global/config/JwtAuthenticationFilter.java
  src/main/java/com/afterburner/global/config/SecurityConfig.java
Labels: 진행 중

#3 chore: add common package for shared enums and rename: Study Package rename
  src/main/java/com/afterburner/common/enums/PostStatus.java
  src/main/java/com/afterburner/common/enums/TeamMemberRole.java
  src/main/java/com/afterburner/study/controller/StudyController.java
  src/main/java/com/afterburner/study/controller/StudytController.java
  src/main/java/com/afterburner/study/model/Study.java
  src/main/java/com/afterburner/study/model/StudyDTO.java
  src/main/java/com/afterburner/study/model/dto/StudyDTO.java
  src/main/java/com/afterburner/study/model/entity/StudyEntity.java
Labels: 진행 중

#14 style:community
  src/main/java/com/afterburner/community/model/Community.java
  src/main/java/com/afterburner/community/model/CommunityDTO.java
  src/main/java/com/afterburner/community/model/CommunityStatus.java
  src/main/java/com/afterburner/community/service/CommunityService.java
  src/main/resources/application.properties
Labels: 진행 중

#13 feat:notice
  src/main/java/com/afterburner/common/enums/PostStatus.java
  src/main/java/com/afterburner/common/enums/TeamMemberRole.java
  src/main/java/com/afterburner/notice/controller/NoticeController.java
  src/main/java/com/afterburner/notice/model/Notice.java
  src/main/java/com/afterburner/notice/model/NoticeDTO.java
  src/main/java/com/afterburner/notice/repository/NoticeRepository.java
  src/main/java/com/afterburner/notice/service/NoticeService.java
  src/main/java/com/afterburner/study/controller/StudyController.java
  src/main/java/com/afterburner/study/model/dto/StudyDTO.java
  src/main/java/com/afterburner/study/model/entity/StudyEntity.java
Labels: 진행 중

#15 feat: common api status code classes
  src/main/java/com/afterburner/common/codes/ErrorCode.java
  src/main/java/com/afterburner/common/codes/ResponseCode.java
  src/main/java/com/afterburner/common/codes/SuccessCode.java
  src/main/java/com/afterburner/common/response/ApiResponse.java
  src/main/java/com/afterburner/common/response/ErrorResponse.java
  src/main/java/com/afterburner/global/exception/GlobalException.java
  src/main/java/com/afterburner/study/controller/StudyController.java
Labels: 완료

#17 Feat/study group
  src/main/java/com/afterburner/global/exception/GlobalExceptionHandler.java
  src/main/java/com/afterburner/study/controller/StudyController.java
  src/main/java/com/afterburner/study/model/dto/StudyDTO.java
  src/main/java/com/afterburner/study/model/entity/StudyEntity.java
  src/main/java/com/afterburner/studygroup/controller/StudyGroupController.java
  src/main/java/com/afterburner/studygroup/model/dto/StudyGroupDTO.java
  src/main/java/com/afterburner/studygroup/model/entity/StudyGroupCategory.java
  src/main/java/com/afterburner/studygroup/model/entity/StudyGroupEntity.java
  src/main/java/com/afterburner/studygroup/repository/StudyGroupRepository.java
  src/main/java/com/afterburner/studygroup/service/StudyGroupService.java
Labels: 진행 중

#19 fix:community
  src/main/java/com/afterburner/community/controller/CommunityController.java
  src/main/java/com/afterburner/community/model/Community.java
  src/main/java/com/afterburner/community/service/CommunityService.java
Labels: 진행 중

#18 feat:SwaggerConfig
  src/main/java/com/afterburner/global/config/SwaggerConfig.java
Labels: 완료

#21 fix:Notice
  src/main/java/com/afterburner/notice/controller/NoticeController.java
  src/main/java/com/afterburner/notice/model/Notice.java
  src/main/java/com/afterburner/notice/service/NoticeService.java
Labels: 진행 중

#22 fix:community delete
  src/main/java/com/afterburner/community/controller/CommunityController.java
  src/main/java/com/afterburner/community/model/Community.java
  src/main/java/com/afterburner/community/model/CommunityDTO.java
  src/main/java/com/afterburner/community/service/CommunityService.java
Labels: 진행 중

#23 Feat/project
  build.gradle
  src/main/java/com/afterburner/project/controller/ProjectController.java
  src/main/java/com/afterburner/project/model/Project.java
  src/main/java/com/afterburner/project/model/ProjectDTO.java
  src/main/java/com/afterburner/project/repository/ProjectRepository.java
  src/main/java/com/afterburner/project/service/ProjectService.java
Labels: 진행 중

#24 feat:projectNotFoundException, TechStackException, errorCode
  src/main/java/com/afterburner/common/codes/ErrorCode.java
  src/main/java/com/afterburner/global/exception/GlobalExceptionHandler.java
  src/main/java/com/afterburner/global/exception/ProjectNotFoundException.java
  src/main/java/com/afterburner/global/exception/TechStackConversionException.java
Labels: 진행 중

#25 fix:community valid, notice valid, project valid
  src/main/java/com/afterburner/community/model/CommunityDTO.java
  src/main/java/com/afterburner/notice/model/NoticeDTO.java
  src/main/java/com/afterburner/project/model/ProjectDTO.java
Labels: 진행 중

#26 fix:project service
  src/main/java/com/afterburner/project/service/ProjectService.java
Labels: 진행 중

#30 feat: report board
  src/main/java/com/afterburner/report/controller/ReportController.java
  src/main/java/com/afterburner/report/model/dto/ReportDTO.java
  src/main/java/com/afterburner/report/model/entity/ReportEntity.java
  src/main/java/com/afterburner/report/model/entity/ReportStatus.java
  src/main/java/com/afterburner/report/repository/ReportRepository.java
  src/main/java/com/afterburner/report/service/ReportService.java
Labels: 완료

#31 style: study-group 줄바꿈 및 띄어쓰기
  src/main/java/com/afterburner/studygroup/controller/StudyGroupController.java
  src/main/java/com/afterburner/studygroup/model/entity/StudyGroupEntity.java
Labels: 완료

#33 feat:ProjectTeam
  src/main/java/com/afterburner/global/exception/GlobalExceptionHandler.java
  src/main/java/com/afterburner/global/exception/TeamMemberNotFoundException.java
  src/main/java/com/afterburner/projectTeam/controller/ProjectTeamController.java
  src/main/java/com/afterburner/projectTeam/model/ProjectTeam.java
  src/main/java/com/afterburner/projectTeam/model/ProjectTeamDTO.java
  src/main/java/com/afterburner/projectTeam/model/ProjectTeamPart.java
  src/main/java/com/afterburner/projectTeam/repository/ProjectTeamRepository.java
  src/main/java/com/afterburner/projectTeam/service/ProjectTeamService.java
Labels: 진행 중

#34 feat : login
  src/main/java/com/afterburner/AfterburnerBackendApplication.java
  src/main/java/com/afterburner/global/config/JwtAuthenticationFilter.java
  src/main/java/com/afterburner/global/config/SecurityConfig.java
  src/main/java/com/afterburner/oauth/config/AppProperties.java
  src/main/java/com/afterburner/oauth/config/SecurityConfig.java
  src/main/java/com/afterburner/oauth/config/WebMvcConfig.java
  src/main/java/com/afterburner/oauth/controller/AuthController.java
  src/main/java/com/afterburner/oauth/controller/UserController.java
  src/main/java/com/afterburner/oauth/exception/BadRequestException.java
  src/main/java/com/afterburner/oauth/exception/OAuth2AuthenticationProcessingException.java
  src/main/java/com/afterburner/oauth/exception/ResourceNotFoundException.java
  src/main/java/com/afterburner/oauth/model/AuthProvider.java
  src/main/java/com/afterburner/oauth/model/User.java
  src/main/java/com/afterburner/oauth/payload/ApiResponse.java
  src/main/java/com/afterburner/oauth/payload/AuthResponse.java
  src/main/java/com/afterburner/oauth/payload/LoginRequest.java
  src/main/java/com/afterburner/oauth/payload/SignUpRequest.java
  src/main/java/com/afterburner/oauth/repository/UserRepository.java
  src/main/java/com/afterburner/oauth/security/CurrentUser.java
  src/main/java/com/afterburner/oauth/security/CustomUserDetailsService.java
  src/main/java/com/afterburner/oauth/security/RestAuthenticationEntryPoint.java
  src/main/java/com/afterburner/oauth/security/TokenAuthenticationFilter.java
  src/main/java/com/afterburner/oauth/security/TokenProvider.java
  src/main/java/com/afterburner/oauth/security/UserPrincipal.java
  src/main/java/com/afterburner/oauth/security/oauth2/CustomOAuth2UserService.java
  src/main/java/com/afterburner/oauth/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/afterburner/oauth/security/oauth2/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/afterburner/oauth/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/afterburner/oauth/security/oauth2/user/FacebookOAuth2UserInfo.java
  src/main/java/com/afterburner/oauth/security/oauth2/user/GithubOAuth2UserInfo.java
  src/main/java/com/afterburner/oauth/security/oauth2/user/GoogleOAuth2UserInfo.java
  src/main/java/com/afterburner/oauth/security/oauth2/user/OAuth2UserInfo.java
  src/main/java/com/afterburner/oauth/security/oauth2/user/OAuth2UserInfoFactory.java
  src/main/java/com/afterburner/oauth/util/CookieUtils.java
Labels: 진행 중, 완료

#36 style:ProjectTeam, Project entity
  src/main/java/com/afterburner/project/model/Project.java
  src/main/java/com/afterburner/projectTeam/model/ProjectTeam.java
Labels: 진행 중

#39 feat:project comments
  src/main/java/com/afterburner/project/projectComment/controller/ProjectCommentsController.java
  src/main/java/com/afterburner/project/projectComment/model/ProjectComments.java
  src/main/java/com/afterburner/project/projectComment/model/ProjectCommentsDTO.java
  src/main/java/com/afterburner/project/projectComment/repository/ProjectCommentsRepository.java
  src/main/java/com/afterburner/project/projectComment/service/ProjectCommentsService.java
Labels: 진행 중

#40 fix:projectTeam
  src/main/java/com/afterburner/projectTeam/controller/ProjectTeamController.java
  src/main/java/com/afterburner/projectTeam/model/ProjectTeam.java
  src/main/java/com/afterburner/projectTeam/model/ProjectTeamDTO.java
  src/main/java/com/afterburner/projectTeam/model/ProjectTeamMember.java
  src/main/java/com/afterburner/projectTeam/repository/ProjectTeamRepository.java
  src/main/java/com/afterburner/projectTeam/service/ProjectTeamService.java
Labels: 진행 중

#41 fix:projectTeam get
  src/main/java/com/afterburner/projectTeam/repository/ProjectTeamRepository.java
  src/main/java/com/afterburner/projectTeam/service/ProjectTeamService.java
Labels: 진행 중

#42 fix:project
  src/main/java/com/afterburner/project/controller/ProjectController.java
  src/main/java/com/afterburner/project/model/Project.java
  src/main/java/com/afterburner/project/model/ProjectDTO.java
  src/main/java/com/afterburner/project/repository/ProjectRepository.java
  src/main/java/com/afterburner/project/service/ProjectService.java
Labels: 진행 중, 업그레이드

#43 fix:project
  src/main/java/com/afterburner/project/repository/ProjectRepository.java
  src/main/java/com/afterburner/project/service/ProjectService.java
Labels: 진행 중

#45 Feat/community comment
  src/main/java/com/afterburner/community/communityComment/controller/CommunityCommentsController.java
  src/main/java/com/afterburner/community/communityComment/repository/CommunityCommentsRepository.java
  src/main/java/com/afterburner/community/communityComment/service/CommunityCommentsService.java
Labels: 진행 중

#46 fix/project team
  src/main/java/com/afterburner/projectTeam/repository/ProjectTeamRepository.java
  src/main/java/com/afterburner/projectTeam/service/ProjectTeamService.java
Labels: 진행 중

#47 feat: 팀원 생성 로직
  src/main/java/com/afterburner/studygroup/service/StudyGroupService.java
  src/main/java/com/afterburner/studygroup_team/controller/StudyGroupTeamController.java
  src/main/java/com/afterburner/studygroup_team/model/dto/StudyGroupTeamDTO.java
  src/main/java/com/afterburner/studygroup_team/model/entity/StudyGroupTeamEntity.java
  src/main/java/com/afterburner/studygroup_team/repository/StudyGroupTeamRepository.java
  src/main/java/com/afterburner/studygroup_team/service/StudyGroupTeamService.java
Labels: 진행 중

#48 fix:notice
  src/main/java/com/afterburner/notice/controller/NoticeController.java
  src/main/java/com/afterburner/notice/model/Notice.java
  src/main/java/com/afterburner/notice/model/NoticeDTO.java
  src/main/java/com/afterburner/notice/service/NoticeService.java
Labels: 진행 중
